sudo: required

language: go 

services:
  - docker
  - mysql

before_script:
  - set -o pipefail

script:
  
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then 
      echo "Pull request detected - running unit tests" &&
      make test;
    elif [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "Deploying services to production";
    fi

