sudo: required

language: go 

services:
  - docker
  - mysql

before_script:
  - set -o pipefail

script:
  
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then 
      echo "Pull request detected - running unit tests" &&
      ip addr show &&
      cat ~travis/.my.cnf &&
      cat /var/run/mysqld/mysqld.sock &&
      make test;
    elif [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "Deploying services to production";
    else
      echo "No deployment necessary";
    fi

